apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: private  # Specify the namespace here
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"  # 500 milliCPU units (0.5 CPU cores)
            memory: "512Mi"  # 512 Mebibytes
          requests:
            cpu: "200m"  # 200 milliCPU units (0.2 CPU cores)
            memory: "256Mi"  # 256 Mebibytes

